### ISSUE TITLE
Leyenda Agua

### ISSUE THREAD

**Issue by sofialog** [geraldo/rubi_consums#11]
Buscar rangos para las leyendas de agua

**Comment by geraldo** [comment]
Dicen mejor usar uno de azules de https://colorbrewer2.org

Tener en cuenta que siempre necesitamos mostrar:

- no tenemos datos
- no mostramos por secreto estadístico

**Comment by geraldo** [comment]
Hay que buscar otros rangos, los de Electricitat i Gas no funcionan y ahora mismo todo está con el mismo azul.
