### ISSUE TITLE
Correccions 05/06

### ISSUE THREAD

**Issue by sofialog** [geraldo/rubi_consums#12]
- [x] Accesos por parcela (count con capa de accesos "id_acces"). Categorizado por cantidad.
- [x] Para cada consumo (electricidad, gas, agua i "global"), 2 columnas: año inicial y final con datos.
- [x] Vista para cada consumo: cuantas parcelas hay con contador... Categorizado por cantidad.
- [x] Crear campos nuevos con diferencia del año referencia (2016).
- [x] Crear campos para contar suministros activos (llum, gas y agua) por parcela
- [x] Crear campos para contar suministros activos (llum, gas y agua) por acceso

**Comment by carlospsig** [comment]
- [ ] Crear vistas o tablas que generen estos datos
![image](https://github.com/geraldo/rubi_consums/assets/5272165/32e69cfd-8714-4808-9851-748afc11e2bd)
