### ISSUE TITLE
ITE

### ISSUE THREAD

**Issue by geraldo** [geraldo/rubi_consums#16]
dades > ites, columna estat

**Comment by sofialog** [comment]
He añadido geometría a la tabla y he hecho un degradado por el campo "estat_final" (o parecido, tengo que comprobarlo cuando tenga conexión). He agrupado todas las de _apte_ como apte, _Denegatoria_ como no apte i _null_ como no consta. Ha quedado una que no sé en que grupo donde ponerla.

**Comment by geraldo** [comment]
Perfecto! En todo caso hay que moverla al grupo Edificis i Infrastructuras
