### ISSUE TITLE
Llegenda Geoportal

### ISSUE THREAD

**Issue by geraldo** [geraldo/rubi_consums#9]
Irene Perez Bort manda eso:

- Any construcció edifici (es poden marcar varies opcions. Segons el que es trii aquí et mostrarà la resta d’opcions triades)
  - Abans de l’any 1980
  - Entre el 1980 i 2006
  - Entre el 2007 i el 2013
  - Entre el 2014 al 2019
  - Posterior al 2019
- Consum real parcela - Any dades (desplegable)
  - Electricitat i gas
    - Consum per m2 i habitatge (kWh/m2*habitatge*any) – que no es tingui en compte en el càlcul els m2 per sota de rasant!!
    Mostrar la classificació en 5 percentils
    Cal diferenciar d’entre els que no tenim dades (no dades) i el que les dades no es mnostren per secret estadístic (secret estadístic)
    - Consum per m2 construït (kWh/m2*any)
    Captura Irene: ![capes](https://github.com/geraldo/rubi_consums/assets/336371/15ae4f6b-8e67-4dac-ac64-73b6919a3f51)
    Cal diferenciar d’entre els que no tenim dades (no dades) i el que les dades no es mnostren per secret estadístic (secret estadístic)
    - Evolució del consum  (%) respecte del 2016.
    Mostrar la classificació en 5 percentils
  - Aigua
    - Consum de la parcela (m3/parcela*any)
    Mostrar la classificació en 5 percentils percentils
    - Consum per persona i dia (m3/persona*dia)  à El Josep us passarà la fòrmula de càlcul en breu, pq sembla que no es calcula amb els empadronats sinó que es fa algun tipus de correcció.
    Fer el primer tall fins a 0,2 m3/persona*dia ja que és el que està permés en estat de sequera.  La resta fer la divisió per quartils.
    - Evolució del consum  (%) respecte del 2016.
    Mostrar la classificació per 5 percentils
- Instal·lació Fotovoltaica (marcador)
- Inspecció tècnica de l’edifici (trama)
  - No consta
  - Apte
  - No apte
- Capes de refèrencia
  - Topogràfic
  - Ortofoto
  - ...

**Comment by geraldo** [comment]
@sofialog los que ahora llamaste "llum", se deberían llamar "electricitat"

**Comment by geraldo** [comment]
@carlospsig qué capa dejamos como predefinida?

**Comment by carlospsig** [comment]
Creo que acordamos dejar por defecto el global por m² del último año que tengamos

**Comment by geraldo** [comment]
@sofialog Cambios acordados en la reunión del 12/6:

- [ ] Secreto estadístico: color blanco
- [ ] Falta capa "Consum per m2 i habitatge (kWh/m2*habitatge*any)"
- [ ] Datos 2022 Aigua
- [ ] Añadimos un aviso para 2021 y 2022 diciendo que se van complementando los datos 
- [ ] Dejamos por definición:
  - 2020 Elicitricitat i Gas
  - Fotovoltaica
  - ITE
